### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by jasonseu** [fiveai/making-better-mistakes#1]
When will the code release?

**Comment by bertinetto** [comment]
Hi,
Thanks for your interest.
It should be ready within the next 2-3 weeks.

**Comment by palash1992** [comment]
Hi Luca,
Any update on the code release? Also, if it is not ready for a Github release can you send a preliminary version by email as well as the data sets? That will be very helpful!

**Comment by bertinetto** [comment]
Hi Palash,
Sorry for the delay in the release but we got wrapped up with some work.
It shouldn't take much longer!

**Comment by rhomu** [comment]
It's been done :-)
