### ISSUE TITLE
Could the authors share the code to pre-compute the "*_ilsvrc_distances.pkl.xz" files?

### ISSUE THREAD

**Issue by leoshine** [fiveai/making-better-mistakes#3]
I am not sure what are the distances stored in these files.
I tried to compute the shortest_path_length based on Imagenet hierarchy, but get similar but different numbers:

For example, in tiered_imagenet_ilsvrc_distances.pkl.xz:

| key | sotred_dist | shortest_path_length |
|-----|-------------|----------------------|
|(n02090379,n02168699): | 14  |  9   |  
|(n03125870,n04409515): | 7   | 8    | 
|(n02395003,n02791124): | 15  |  10  |   
|(n03803284,n04557648): | 7   | 8    | 
|(n09468604,n01525720): | 8   | 11   |  
|(n03347037,n03445924): | 11  |  9   |  
|(n02489166,n02009912): | 11  |  8   |  
|(n02480855,n07768694): | 13  |  10  |   
|(n04127249,n02229544): | 13  |  10  |   
|(n04552348,n02093859): | 19  |  10  |   
|(n02808440,n03866082): | 10  |  9   |  
|(n04401088,n01498041): | 12  |  10  |   
|(n03146219,n04429376): | 11  |  9   |  
|(n04049303,n02011460): | 14  |  10  |   
|(n02692877,n02410509): | 17  |  10  |   
|(n07590611,n02437616): | 15  |  12  |   
|(n04579145,n02104523): | 17  |  10  |   
|(n03980874,n03670208): | 14  |  9   |  
|(n03457902,n03447447): | 10  |  9   |  
|(n00002684,n07753113): | 5   | 12   |  
|(n04202417,n04356056): | 9   | 9    | 
|(n02279972,n02129165): | 12  |  9   |  
|(n09421951,n07718747): | 7   | 12   |  
|(n02089555,n02121808): | 8   | 6    | 
|(n04347754,n03944341): | 12  |  8   |  
|(n03614532,n02233338): | 12  |  10  |   
|(n03414162,n03990474): | 5   | 8    | 
|(n02093647,n02095412): | 2   | 3    | 
|(n07714571,n02051845): | 13  |  12  |   
|(n02028035,n07714990): | 15  |  12  |   
|(n03891251,n04557648): | 8   | 8    | 
|(n04311174,n04524313): | 6   | 8    | 
|(n04208210,n02370806): | 12  |  10  |   
|(n02089555,n01674464): | 11  |  8   |  
|(n01482071,n02090622): | 11  |  8   |  
|(n03614532,n07829412): | 12  |  12  |   
|(n04550184,n01846331): | 12  |  10  |   
|(n03419014,n02128925): | 14  |  10  |   
|(n03146219,n07715103): | 12  |  12  |   
|(n03928116,n04081281): | 8   | 9    | 
|(n02091467,n07695965): | 18  |  12  |   
|(n04347754,n02087122): | 18  |  10  |   
|(n04550184,n04326547): | 8   | 9    | 
|(n02951358,n03942813): | 11  |  8   |  
|(n02526121,n04515003): | 14  |  10  |   
|(n03930630,n02099712): | 21  |  10  |   
|(n04479046,n02865351): | 5   | 6    | 
|(n02028035,n01676755): | 10  |  8   |  
|(n02704792,n04507155): | 11  |  9   |  
|(n02536864,n02933112): | 12  |  10  |

**Comment by rhomu** [comment]
Thanks for your question! We give our recipe to compute the distances in the supplementary information of our paper (section D). In particular we do not take the shortest path between the leaf nodes and the root node but rather take the longest path and resolve any conflict manually.

We have not included the corresponding script out in the repository because it depends on external data (e.g. wordnet edges definition, etc) and could not be run out of the box (we want to keep the public repo clean). However, we are happy to provide them to you if you send us a quick email!

**Comment by 07Agarg** [comment]
Hi @rhomu , Thanks for the great repository!

It could be very kind of you to provide me with the code to compute the distances in tiered_imagenet_ilsvrc_distances.pkl.xz,. 

Also, I am unclear on how to generate the file for tiered_imagenet_tree.pkl, and tiered_imagenet_isa. If possible, please include the scripts to generate these files too. 

My Email ID is: ashimag@iiitd.ac.in

Thanks again!
