### ISSUE TITLE
Error while training model with HXE loss 

### ISSUE THREAD

**Issue by sgk98** [fiveai/making-better-mistakes#4]
Hello,
I was trying to run the HXE experiments for tiered-ImageNet-H, and I got this error:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 12]], which is output 0 of SqueezeBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
Enabling anomaly detection, the error is shown in the following line in ```losses.py```:
```num[idx] = -torch.log(num[idx] / den[idx])```.
In particular, the issue seems to be with ```num[idx]``` somehow is being considered an in-place operation which seems weird since all the other methods(DeViSE,Soft-labels, YOLOv2 and Barz&Denzler run smoothly).

It would be great if you could help me out with this issue.
Thanks!

**Comment by rhomu** [comment]
That's weird indeed! How do you run the code? Are you using the docker container provided? Also could you give me your pytorch version?

**Comment by sgk98** [comment]
I was using PyTorch 1.2.0(without Docker) where I was facing these issues. 
Switching to using the conda environment provided seems to have solved the issue, although I'm not sure what was the difference between PyTorch 1.1 and 1.2
Thanks for your help!.
