### ISSUE TITLE
Authors, please share the code for pre-computing distances!

### ISSUE THREAD

**Issue by 07Agarg** [fiveai/making-better-mistakes#7]
Hi @rhomu , Thanks for the great repository!

It could be very kind of you to provide me with the code to compute the distances in tiered_imagenet_ilsvrc_distances.pkl.xz,.

Also, I am unclear on how to generate the file for tiered_imagenet_tree.pkl, and tiered_imagenet_isa. If possible, please include the scripts to generate these files too.

My Email ID is: ashimag@iiitd.ac.in

Thanks again!

**Comment by rhomu** [comment]
Hello!

Thanks for checking our repo :-)

The `isa` file can be generated from the corresponding `isa` file for imagenet which can be obtained from the official website.

I have added the scripts we used to generate the hierarchies in `data/scripts_asis'. Note that they might not work out of the box.

Cheers

**Comment by 07Agarg** [comment]
Thanks a ton, @rhomu !
