### ISSUE TITLE
LCA Distances in the tiered_imagenet_ilsvrc_distances.txt.xz

### ISSUE THREAD

**Issue by 07Agarg** [fiveai/making-better-mistakes#9]
Hello Authors, 

I have used the tiered_imagenet_tree.pkl file to print the following tree. The lowest common ancestor of the leaf nodes **n07831146**  and **n07836838** is **n07829412** which is at distance 1. Whereas in the file tiered_imagenet_ilsvrc_distances.txt.xz you have shared, the LCA distance is 7. ( Please see 5th and 6th leaf nodes **n07831146**  and **n07836838** in the tree).

Did you extend the tree to the finest level and then compute the LCA distances?
The extended tree meaning if the node at coarser-levels has no child nodes, you extend these nodes till the finest level and then compute the LCA distances?  

Thank you so much!
 
![Tree](https://user-images.githubusercontent.com/25235207/146749565-ac5e42b3-295c-4f85-b82d-d39a74e8d895.png)

**Comment by rhomu** [comment]
Hi and thanks for checkout out our repo!

The distance we use is not the distance _to_ the LCA but rather the height of the LCA. Quoting from section 4.2 from our paper: "We use the height of the lowest common ancestor (LCA) between the predicted class and the ground truth as a core severity measure, as originally proposed in the papers describing the creation of ImageNet." Note that the height of a node is not the same as its depth, see eg. https://stackoverflow.com/questions/2603692/what-is-the-difference-between-tree-depth-and-height

Does this answer your question?

**Comment by Depanshu-Sani** [comment]
You mentioned that the LCA distance is defined as the height of the tree rooted at the lowest common ancestor between any two nodes. In the particular case mentioned above, the parent class **n07829412** has only two children and both of them are leaf nodes. Therefore, the height of this subtree is equal to the distance mentioned above, i.e. 1. I am still not sure how we get LCA distance to be 7 in this particular case. Do we artificially extend all the leaf nodes to be at the same level and then do this?

**Discussion >>>>>>**
Case 1: We compute the height of the tree rooted at LCA
Case 2: We compute the maximum path length between LCA and leaf after extending leaf nodes to be at the same level.

Aren't both case 1 and case 2 logically incorrect (arguably)?
Consider the leaf nodes A and B in the following tree. By either of the above methods, the LCA distance between A and B will be 2, which will be the same as the distance between (A,C) and (A,D). But we can clearly see that (A,B) should be closer than (A,C) and (A,D).
![Image](https://github.com/user-attachments/assets/0b94d2d8-da0f-4542-adf3-b2d563fe78f3)
